### ISSUE TITLE
Specify in documentation whether this is cooperative or preemptive multithreading

### ISSUE THREAD

**Issue by carlpaten** [rphmeier/jobsteal#5]
I'd do it myself but I have no idea :)

**Comment by rphmeier** [comment]
Sorry for the long response time. I think this got filed during exam season and flew under the radar ever since. I hadn't heard the terms cooperative/preemptive multithreading before, so I've done a little reading and it seems as though this is preemptive, although to be honest I am not completely clear on how the terms apply to something like a thread pool.

Here are the facts:
- each worker has its own thread
- workers do not yield execution to each other
- once a job has been claimed by a worker, no other workers will perform that job
- worker threads may be subject to context switches by the OS

Which one does it seem like to you?

**Comment by carlpaten** [comment]
> workers do not yield execution to each other

This is roughly the definition of cooperative multithreading. Preemptive threading means that threads can be "preempted" (context-switched) by the scheduler in the middle of an operation.

Thanks for your help :)

**Comment by nikomatsakis** [comment]
I do not think this is cooperative multithreading as the term is usually used. Workers do not explicitly "yield" to one another-- and since the thread pool may have multiple active O/S threads, they can be pre-empted in favor of one another. But it's all a matter of perspective.

**Comment by rphmeier** [comment]
Before I add any statement to the documentation, is there any more information that would be helpful? What significance does a thread pool's multithreading strategy have to a user?

**Comment by carlpaten** [comment]
> What significance does a thread pool's multithreading strategy have to a user?

Two things:
- If it's M:N threading, then doing a blocking operation on one thread can hang another. If it's 1:1 threading, that can't happen. I'm assuming this project is about M:N.
- If it's cooperative M:N, then entering an infinite loop in one thread can hang another. Can't happen with pre-emptive threading, but then synchronization is more difficult; you have no guarantee that any given block of code will execute uninterrupted by a context switch.

**Comment by rphmeier** [comment]
I haven't forgotten about this issue, even though it's laid dormant for quite some time now.

I don't think that either of the terms fully apply here, so I'd prefer not to add a definition to the documentation which doesn't quite fit. Instead, I will just lay out the facts of `jobsteal` and let the user decide if it meets their requirements.
